# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: mholman@cfa.harvard.edu
author_name: Matthew Holman
create_example_module: true
custom_install: true
enforce_style:
- black
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: layup
project_license: MIT
project_name: layup
project_organization: Smithsonian
python_versions:
- '3.11'
- '3.12'
