# This workflow will run daily at 06:45.
# It will install Python dependencies and run tests with a variety of Python versions.
# See documentation for help debugging smoke test issues:
#    https://lincc-ppt.readthedocs.io/en/latest/practices/ci_testing.html#version-culprit

name: Unit test smoke test

on:

  # Runs this workflow automatically
  schedule:
    - cron: 45 6 * * *
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: ['macos-latest','ubuntu-latest']
        python-version: ['3.11', '3.12']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up - ${{ matrix.os }} - Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git submodule update --init
        pip install -e .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        layup bootstrap
    - name: List dependencies
      run: |
        pip list
    - name: Run unit tests with pytest
      run: |
        export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
        python -m pytest
