# This workflow will install Python dependencies, run tests and report code coverage with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit test and code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: ['macos-latest','ubuntu-latest']
        python-version: ['3.11', '3.12']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up - ${{ matrix.os }} - Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git submodule update --init
        pip install -e .
        pip install -e .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        layup bootstrap
    - name: Run unit tests with pytest
      run: |
        export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
        python -m pytest -n auto --cov=layup --cov-report=xml
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
